#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-sphinx_theme_builder
Version  : 0.2.0a14
Release  : 1
URL      : https://files.pythonhosted.org/packages/3e/47/35a2e2b57a050e3d92f6325d789d3803ee7bd020fbb14a48b0d276ba5822/sphinx-theme-builder-0.2.0a14.tar.gz
Source0  : https://files.pythonhosted.org/packages/3e/47/35a2e2b57a050e3d92f6325d789d3803ee7bd020fbb14a48b0d276ba5822/sphinx-theme-builder-0.2.0a14.tar.gz
Summary  : A tool for authoring Sphinx themes with a simple (opinionated) workflow.
Group    : Development/Tools
License  : MIT
Requires: pypi-sphinx_theme_builder-bin = %{version}-%{release}
Requires: pypi-sphinx_theme_builder-license = %{version}-%{release}
Requires: pypi-sphinx_theme_builder-python = %{version}-%{release}
Requires: pypi-sphinx_theme_builder-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(flit_core)

%description
# Sphinx Theme Builder
<!-- start-elevator-pitch -->
Streamline the Sphinx theme development workflow, by building upon existing standardised tools.

%package bin
Summary: bin components for the pypi-sphinx_theme_builder package.
Group: Binaries
Requires: pypi-sphinx_theme_builder-license = %{version}-%{release}

%description bin
bin components for the pypi-sphinx_theme_builder package.


%package license
Summary: license components for the pypi-sphinx_theme_builder package.
Group: Default

%description license
license components for the pypi-sphinx_theme_builder package.


%package python
Summary: python components for the pypi-sphinx_theme_builder package.
Group: Default
Requires: pypi-sphinx_theme_builder-python3 = %{version}-%{release}

%description python
python components for the pypi-sphinx_theme_builder package.


%package python3
Summary: python3 components for the pypi-sphinx_theme_builder package.
Group: Default
Requires: python3-core
Provides: pypi(sphinx_theme_builder)
Requires: pypi(nodeenv)
Requires: pypi(packaging)
Requires: pypi(pep621)
Requires: pypi(rich)
Requires: pypi(setuptools)
Requires: pypi(tomli)

%description python3
python3 components for the pypi-sphinx_theme_builder package.


%prep
%setup -q -n sphinx-theme-builder-0.2.0a14
cd %{_builddir}/sphinx-theme-builder-0.2.0a14

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1650422172
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-sphinx_theme_builder
cp %{_builddir}/sphinx-theme-builder-0.2.0a14/LICENSE %{buildroot}/usr/share/package-licenses/pypi-sphinx_theme_builder/28fe1f46ac6435fe4c4fda18cd15499926faefd5
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/stb

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-sphinx_theme_builder/28fe1f46ac6435fe4c4fda18cd15499926faefd5

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
